default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: oocranv2
  password: oocranv2 
  pool: 5

development:
  <<: *default
  database: oocran_development    
test:
  <<: *default
  database: oocran_test    
production:
  <<: *default 
  database: oocran_production    
